apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange-buggy
  labels:
    app: currency-exchange
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: currency-exchange
  template:
    metadata:
      labels:
        app: currency-exchange
        version: v2
    spec:
      containers:
      - name: currency-exchange
        image: {{ .Values.currencyexchange.image}}
        ports:
        - containerPort: {{ .Values.currencyexchange.port}}
