apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange
  labels:
    app: currency-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-exchange
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
      - name: currency-exchange
        image: {{ .Values.currencyexchange.image}}
        ports:
        - containerPort: {{ .Values.currencyexchange.port}}
---
apiVersion: v1
kind: Service
metadata:
  name: currency-exchange
  labels:
    app: currency-exchange
spec:
  type: {{ .Values.currencyexchange.servicetype}}
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: currency-exchange