apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress-1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.gateway.currencyexchangepath}}
        backend:
          serviceName: currency-exchange
          servicePort: 8080          
      - path: {{ .Values.gateway.currencyconversionpath}}
        backend:
          serviceName: currency-conversion
          servicePort: 8080                    