{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helloworld-ravi.serviceAccountName" . }}
  labels:
{{ include "helloworld-ravi.labels" . | indent 4 }}
{{- end -}}
